apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coffee-ingress
spec:
  rules:
  - host: coffee.example.com
    http:
      paths:
      - backend:
          serviceName: tea
          servicePort: 80
        path: /tea
      - backend:
          serviceName: coffee
          servicePort: 80
        path: /coffee
