apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation
spec:
  hosts:
  - recommendation
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 2s
    route:
    - destination:
        host: recommendation
        subset: v1
      weight: 90
    - destination:
        host: recommendation
        subset: v2
      weight: 10
