apiVersion: v1
kind: Service
metadata:
  labels:
    app: coffee
  name: coffee
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: coffee
  type: ClusterIP
