apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: coffee
  name: coffee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - image: nginxdemos/hello
        imagePullPolicy: Always
        name: coffee
        ports:
        - containerPort: 80
          protocol: TCP
