apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tea
  name: tea
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - image: nginxdemos/hello
        imagePullPolicy: Always
        name: tea
        ports:
        - containerPort: 80
          protocol: TCP
