apiVersion: v1
kind: Pod
metadata:
  labels:
    app: readiness
  name: readiness-http
spec:
  containers:
  - name: readiness
    args:
    - /server
    image: gcr.io/google_containers/liveness
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 2
      initialDelaySeconds: 3
      periodSeconds: 2

