apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
  namespace: default
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - 'customer-tutorial.130.211.213.14.xip.io'
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /
    route:
    - destination:
        host: customer
        port:
          number: 8080
