apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: redis
spec:
  replicas: 10
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2.8-alpine
        ports:
        - containerPort: 6379

