apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ghost
  template:
    metadata:
      labels:
        name: ghost
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: development
        image: ghost:0.10
        imagePullPolicy: IfNotPresent
        name: ghost
        ports:
        - containerPort: 2368
          name: http-server
        volumeMounts:
        - mountPath: /var/lib/ghost
          name: ghost
          subPath: ghost
      volumes:
      - name: ghost
        persistentVolumeClaim:
          claimName: ghost-claim
