apiVersion: v1
kind: Service
metadata:
  labels:
    name: ghost
  name: ghost
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 2368
  selector:
    name: ghost
  type: LoadBalancer
